version: "3"
services:
  database:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
